Add a development environment for the flask backend
iScsc/iscsc.fr pull request #104
Opened 2023-05-16 23:17 UTC by ctmbl

I just squash and rebase my branch form #86 (still not merged) and then update it to adapt it to a flask backend, just like I did for #88 
I also fixed an issue I didn't saw in #88, anyway this was a first shot, not a definitive prod environment.
However this PR should do as a definitive development environment, modulo some new commits in #86 post b0ab27d

2023-05-17 07:03 UTC, ctmbl commented
No worries we can wait for tonight!

2023-05-17 17:01 UTC, atxr requested changes

2023-05-17 17:01 UTC, atxr commented on .env.example
> +REACT_APP_API_URL="http://<name of the backend container in docker network | localhost>:$NODE_PORT"
```suggestion
REACT_APP_API_URL="http://<name of the backend container in docker network | localhost>:$FLASK_RUN_PORT"
```

2023-05-19 09:21 UTC, atxr commented
All clear then! :racehorse:

2023-05-19 09:21 UTC, atxr approved these changes

2023-05-19 09:26 UTC, merged