Updating license ISC to LICENSE.MD in ./backend
iScsc/iscsc.fr pull request #50
Opened 2022-11-22 02:23 UTC by vSt11

Like specified, it needed to be simply updated

2022-11-22 15:53 UTC, ctmbl requested changes

2022-11-22 15:57 UTC, ctmbl commented
I forgot to mention it, but maybe we should also update `author`? see [the doc](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#people-fields-author-contributors) about `person` `author` and `contributors`, but I'm fine with letting `Alexandre Tullot` for now and further updating it on later PRs (contributing to the backend I mean)

2022-11-22 16:02 UTC, amtoine commented on backend/package.json
> +  "license": "LICENSE.MD",
:laughing: 
then it's the type of license and not the license filename :+1:

2022-11-23 18:49 UTC, vSt11 commented
For the author field, do you allow me to give your email @atxr ? If so, you can reply it to me here then. 
I don't really know all the people I should credit for now, maybe it's better to update it later, in a different issue ?

2022-11-25 01:28 UTC, ctmbl approved these changes
After reading [our license](https://github.com/iScsc/iscsc.fr/blob/main/LICENSE.MD) (really just the beginning) I think sticking with `GPL-3.0-only` is fine :+1: 

As for the `author` field I would like to see @atxr opinion first :wink:
But as is this PR is good to merge according to me!

2022-11-26 11:06 UTC, atxr reviewed
Aha I'm totally fine about being the author of this repo, even if it's the whole club :wink: 
About the mail, I don't have any problem, but I think putting the iscsc mail would be better
supaerocsclub@gmail.com

2022-11-28 19:29 UTC, atxr approved these changes
@ctmbl is right, this author discussion is out of the scope of #50 
Let's merge this :rocket:

2022-11-28 19:30 UTC, merged