Security updates
iScsc/iscsc.fr pull request #51
Opened 2022-11-25 14:52 UTC by atxr

This PR brings security updates about:
- Dependabot alerts on some dependencies used in the frontend
-  Snyk scan on the production app, which found vulnerabilities on the nginx-alpine image

This changes haven't been tested yet in production mode.
Close #39 and should resolve Dependabot alerts

2022-11-26 03:27 UTC, ctmbl requested changes
This currently doesn't work in production mode:
```
> sudo docker-compose --env-file .env.production up -d --build
...
 > [iscscfr-react-app 7/7] RUN npm run build:
#0 0.880
#0 0.880 > iscsc.fr-frontend@0.1.0 build
#0 0.880 > react-scripts build
#0 0.880
#0 0.889 sh: 1: react-scripts: not found
------
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 127
```

2022-11-26 03:39 UTC, ctmbl commented
This PR also arises an important question: in such cases where we found a vulnerability and want to patch it, shouldn't we release a `v0.1.1` rapidly to patch the vulnerability on the real website or should we wait for `v0.2.0`.

In the case we want to release `v0.1.1` should we:
 - **A**: merge this PR in `main` and release previously merged PRs (from `v0.1.0`) with it
 - **B**: merge on a specific branch (let's say `released`) which is based on `v0.1.0` and then merge `release` into `main`?

Following `git log --oneline ...` format:
**A**:
```
* (main, v0.1.1) this PR
* commit
* commit
* (v0.1.0) Bump to version 0.1.0
```

**B**:
```
* (main) Merged with `released`
|\
* | commit
* | commit
| * (released, v0.1.1) this PR
|/
* (v0.1.0) Bump to version 0.1.0
```

2022-11-26 11:09 UTC, atxr commented
> 

Oh indeed let me fix this :thinking: 
Did you experience any issue with the SSL certificates? Or maybe you tested it on the server directly.

2022-11-26 11:14 UTC, atxr commented
> This PR also arises an important question: in such cases where we found a vulnerability and want to patch it, shouldn't we release a `v0.1.1` rapidly to patch the vulnerability on the real website or should we wait for `v0.2.0`.
> 
> In the case we want to release `v0.1.1` should we:
> 
>     * **A**: merge this PR in `main` and release previously merged PRs (from `v0.1.0`) with it
> 
>     * **B**: merge on a specific branch (let's say `released`) which is based on `v0.1.0` and then merge `release` into `main`?
> 
> 
> Following `git log --oneline ...` format: **A**:
> 
> ```
> * (main, v0.1.1) this PR
> * commit
> * commit
> * (v0.1.0) Bump to version 0.1.0
> ```
> 
> **B**:
> 
> ```
> * (main) Merged with `released`
> |\
> * | commit
> * | commit
> | * (released, v0.1.1) this PR
> |/
> * (v0.1.0) Bump to version 0.1.0
> ```

This is a very good question and my answer to this is:
![image](https://user-images.githubusercontent.com/27704776/204085868-4b3697c1-9b7f-495c-8abf-0c7bb376a6c9.png)

This is based on the git flow you shared to us few month ago
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

2022-11-26 16:29 UTC, amtoine commented
@ctmbl
> This PR also arises an important question: in such cases where we found a vulnerability and want to patch it, shouldn't we release a `v0.1.1` rapidly to patch the vulnerability on the real website or should we wait for `v0.2.0`.
> 
> In the case we want to release `v0.1.1` should we:
> 
> * **A**: merge this PR in `main` and release previously merged PRs (from `v0.1.0`) with it
> * **B**: merge on a specific branch (let's say `released`) which is based on `v0.1.0` and then merge `release` into `main`?
> 
i would say **B** is great to isolate this patch from the commits merged in partial release PRs, i.e. PRs being merged in between two releases.
and **A** is great if we want to add the other features as well, here that would be 392befa..6d7a9f6 :thinking: 

maybe **B** is better to have rapid security patches in the deployed website.
so i'd say **B** for now with the above :yum: 

@atxr 
> - We currently use the main branch as develop branch.
>
i think it's enough for our projects :thinking:
first of all, **we use the ["feature branch" gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) right?** maybe the ["fork" gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) 'cause it looks similar if some of us use forks?

according to me, the "feature branch" looks right for a small project as ours :+1:
and when reading  the first paragraph of [this](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and [this](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development), i do not know if it would be that great to change to "gitflow"...

it looks quite cool for the orange hotfix, but apart from that i feel the only reason to switch would be to try it out and gain experience in workflows, not really to solve issues in this project :yum: 
which can be a legit reason to switch do not get me wrong :wink: 

> - How to redesign our whole git tree, isn't it too late?
>
we could switch from now on, that wouldn't be a problem :thinking: 
we freeze the version at 6d7a9f6, create a new `develop` branch from there and start the strategy as defined in the links above :+1: 
we can even change the PR branch from within open PRs, e.g. request a merge in `develop` instead of `main` in #47 :ok_hand:

2022-11-26 16:29 UTC, amtoine commented
this is a tricky question :yum:

2022-11-26 16:32 UTC, amtoine commented
and in the end, @atxr and @ctmbl, it's probably not the place to discuss a switch in workflows :eyes:

2022-11-26 16:33 UTC, amtoine reviewed
that looks ok to me
you only changed two versions for the better :ok_hand:

2022-11-28 17:36 UTC, ctmbl requested changes
@atxr 
> Oh indeed let me fix this thinking
EDIT: Fix [62b848b](https://github.com/iScsc/iscsc.fr/pull/51/commits/62b848b87cd34b17f92afb34759c47c29fc42349)

As far as I can tell that worked, but I have 2 limitations: 
 - it seems I can't test SSL certificates on local [see](https://community.letsencrypt.org/t/how-to-use-certbot-using-localhost-name/184126) (that will answer your question)
 - I get the same issue that forbade me to test production mode on #20, all I can tell is that I get the same behaviour, but I strongly advise you to test it yourself 
 
And one request change:
please run `npm install` in frontend because `package-lock.json` isn't up to date, and that point makes me remember we have to deal with #31

2022-11-28 17:37 UTC, ctmbl commented
@atxr @amtoine 

> and in the end, @atxr and @ctmbl, it's probably not the place to discuss a switch in workflows eyes

I totally agree so please continue there: https://github.com/iScsc/iscsc.fr/discussions/54

2022-12-07 00:52 UTC, ctmbl commented
@atxr this PR is almost ready do you have some time to finish it?

2022-12-07 23:13 UTC, atxr commented
> @atxr this PR is almost ready do you have some time to finish it?

I can try yes, but how about the tests? Should I test directly on the server?

2022-12-08 02:23 UTC, ctmbl commented
@atxr 
>  Should I test directly on the server?

for SSL certificates it seems that we don't have much choice for now, we should however look for a better solution, maybe a subdomain to test automatically? we'll have to discuss that in another issue though
So overall my answer is yes I think, but maybe I could give you a hand? (with some supervision ofc)

> please run npm install in frontend

but you should do this first :wink:

Anyway, if you're lacking time right now nevermind it's not an emergency I think (even if it seems severe the blog is quite unknown right now)

2022-12-17 22:30 UTC, atxr commented
The tests were successful and I ran `npm i` for the frontend!
Ready to merge :rocket:

2022-12-19 17:50 UTC, ctmbl approved these changes

2022-12-19 17:51 UTC, ctmbl commented
@atxr tks it's perfect!
Once @amtoine will approve we'll be able to merge it

2022-12-20 12:17 UTC, amtoine commented
@atxr
in [`dc5600e`](https://github.com/iScsc/iscsc.fr/pull/51/commits/dc5600e79dbc9b8286b2221c6312feebd9113690), you simply run
```bash
cd frontend
npm install
```
and that caused changes in `frontend/package-lock.json`? :yum:

2022-12-20 17:13 UTC, atxr commented
> @atxr in [`dc5600e`](https://github.com/iScsc/iscsc.fr/pull/51/commits/dc5600e79dbc9b8286b2221c6312feebd9113690), you simply run
> 
> ```shell
> cd frontend
> npm install
> ```
> 
> and that caused changes in `frontend/package-lock.json`? 😋

Yes exactly

2022-12-20 18:35 UTC, amtoine approved these changes
> Yes exactly, as @ctmbl requested
>
then it's perfect :ok_hand:

2022-12-20 18:36 UTC, merged